language: csharp
mono: none
dotnet: 2.2.105
dist: xenial
script:
 - dotnet publish -c release -r ubuntu.18.04-x64
 - rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/learning-together-api/bin/Release/netcoreapp2.2/ubuntu.18.04-x64/* ltuser@ec2-18-224-56-34.us-east-2.compute.amazonaws.com:/home/ltuser/lt-api
# deploy:
#   skip_cleanup: true
#   provider: script
#   script: dotnet publish -c release -r ubuntu.18.04-x64
#   on:
#     branch: test-travis
before_script:
- openssl aes-256-cbc -K $encrypted_d671cfae17dc_key -iv $encrypted_d671cfae17dc_iv
  -in ltuserssh_rsa.enc -out ./ltuserssh_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./ltuserssh_rsa
- ssh-add ./ltuserssh_rsa
- mkdir -p ~/.ssh  &&  echo "Host *" > ~/.ssh/config && echo " StrictHostKeyChecking no" >> ~/.ssh/config
- ssh-keyscan -H 18.224.56.34 >> ~/.ssh/known_hosts