language: csharp
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet publish -c release -r ubuntu.18.04-x64
  on:
    branch: test-travis
before_deploy:
- openssl aes-256-cbc -K $encrypted_d671cfae17dc_key -iv $encrypted_d671cfae17dc_iv
  -in ltuserssh_rsa.enc -out ./ltuserssh_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./ltuserssh_rsa
- ssh-add ./ltuserssh_rsa
- mkdir -p ~/.ssh  &&  echo "Host *" > ~/.ssh/config && echo " StrictHostKeyChecking no" >> ~/.ssh/config
- ssh-keyscan -H 18.224.56.34 >> ~/.ssh/known_hosts